### ISSUE TITLE
No weights found: While running train.py

### ISSUE THREAD

**Issue by iabhi7** [llSourcell/How_to_make_a_text_summarizer#1]
IOError: Unable to open file (Unable to open file: name = 'data/train.hdf5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

While loading the weights, the weights are not found and I got the above error message.

**Comment by rtlee9** [comment]
Looks like you have to construct and fit a model, then save the resulting weights before there's anything to load. Assuming the IOError came from the load section of the train notebook, you can skip it the first time around or alternatively change `if FN1:` to `if FN1 and (os.path.exists('data/%s.hdf5'%FN1)):`

**Comment by iabhi7** [comment]
Hi @rtlee9 , I already tried that, thanks for your prompt response :)
Also kudos for the numpy importing correction.
Kindly review the other issue that I have created.
